services:
  wd_ft_web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: wd_ft_web
    restart: unless-stopped
    expose:
      - "3004"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
