services:
  app:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: workspace_uat_ft_web
    restart: unless-stopped
    expose:
      - "3004"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
