services:
  app:
    build:
      context: ../..
      dockerfile: apps/docs/Dockerfile
    container_name: workspace_uat_ft_docs
    restart: unless-stopped
    expose:
      - "3002"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
