services:
  workspace_uat_ft_auth:
    build:
      context: ../..
      dockerfile: apps/auth/Dockerfile
    container_name: workspace_uat_ft_auth
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3001"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true  # Use the previously created shared network
