services:
  app:
    build:
      context: ../..
      dockerfile: apps/workspace/Dockerfile
    container_name: workspace_uat_ft_workspace
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3005"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
