services:
  app:
    build:
      context: ../..
      dockerfile: apps/approval-flows/Dockerfile
    container_name: workspace_uat_ft_af
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3006"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
