services:
  app:
    build:
      context: ../..
      dockerfile: apps/hr/Dockerfile
      args:
        NEXT_PUBLIC_AUTH_API: ${NEXT_PUBLIC_AUTH_API}
        NEXT_PUBLIC_AUTH_API_AUTH_DOMAIN: ${NEXT_PUBLIC_AUTH_API_AUTH_DOMAIN}
        NEXT_PUBLIC_WORKSPACE_DOMAIN: ${NEXT_PUBLIC_WORKSPACE_DOMAIN}
        NEXT_PUBLIC_AUTH_API_APPROVAL_FLOWS_DOMAIN: ${NEXT_PUBLIC_AUTH_API_APPROVAL_FLOWS_DOMAIN}
        NEXT_PUBLIC_NETWORK_ENCRYPTION: ${NEXT_PUBLIC_NETWORK_ENCRYPTION}
        NEXT_PUBLIC_NETWORK_ENCRYPTION_KEY: ${NEXT_PUBLIC_NETWORK_ENCRYPTION_KEY}
    container_name: workspace_uat_ft_hr
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3003"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
